name: publish-android

on:
  push:
    tags: [ "android-*-v[0-9]+.[0-9]+.[0-9]+" ]

jobs:

  publish-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - uses: android-actions/setup-android@v2

      - name: Resolve workspace
        run: echo "WORKSPACE=android/$(echo ${{ github.ref_name }} | cut -d- -f2- | rev | cut -d- -f2- | rev)" >> $GITHUB_ENV

      - name: Unpack TapAndPay SDK
        run: cd android && gpg -dq --batch --yes --passphrase ${GPG_PASSPHRASE} tapandpay_sdk.zip.gpg | tar -zx
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - run: ../gradlew test
        working-directory: ${{ env.WORKSPACE }}

      - run: ../gradlew build
        working-directory: ${{ env.WORKSPACE }}

      - run: ../gradlew publish
        working-directory: ${{ env.WORKSPACE }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  publish-docs:
    needs:
      - publish-android
    uses: ./.github/workflows/publish-docs.yml
