name: publish-web

on:
  push:
    tags: [ "web-*-v[0-9]+.[0-9]+.[0-9]+" ]

jobs:

  publish-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - name: Resolve workspace
        run: echo "WORKSPACE=web/$(echo ${{ github.ref_name }} | cut -d- -f2- | rev | cut -d- -f2- | rev)" >> $GITHUB_ENV

      - run: npm ci

      - name: Build packages
        run: |
          [ $WORKSPACE == web/racehorse ] || npm run build --workspace=web/racehorse
          npm run build --workspace=$WORKSPACE

      - run: npm test --workspace=$WORKSPACE

      - run: npm publish --access public
        working-directory: ${{ env.WORKSPACE }}/lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-docs:
    needs:
      - publish-web
    uses: ./.github/workflows/publish-docs.yml
    secrets:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
