name: publish-web

on:
  push:
    tags: [ "web-*-v[0-9]+.[0-9]+.[0-9]+" ]

jobs:

  publish-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - name: Resolve workspace
        run: echo "WORKSPACE=web/$(echo ${{ github.ref_name }} | cut -d- -f2- | rev | cut -d- -f2- | rev)" >> $GITHUB_ENV

      - run: npm ci

      - name: Build packages
        run: |
          [ $WORKSPACE == web/racehorse ] || npm run build --workspace=web/racehorse
          npm run build --workspace=$WORKSPACE

      - run: npm test --workspace=$WORKSPACE

      - run: npm publish --workspace=$WORKSPACE --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
