name: test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

env:
  ANDROID_API_LEVEL: 29

jobs:

  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm test

  test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Unpack TapAndPay SDK
        working-directory: ./android
        run: gpg -dq --batch --yes --passphrase ${GPG_PASSPHRASE} tapandpay_sdk.zip.gpg | tar -zx
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          force-avd-creation: false
          working-directory: ./android/racehorse
          script: ../gradlew connectedCheck

      - name: Run tests
        working-directory: ./android/racehorse
        run: ../gradlew test
